[package]
name = "ppap"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
base64 = "0.23.1"
clap = {version = "4.5.20", features = ["derive"]}
dotenv = "0.15.0"
lettre = "0.11.10"
once_cell = "1.20.2"
rand = "0.8.5"
reqwest = {version = "0.13.1", features = ["json"]}
serde = {version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
serial_test = "4.0.1"
tokio = {version = "1.41.0", features = ["full", "macros"]}
zip = "8.1.0"

[dev-dependencies]
tempfile = "3.13.0"
